# Generated by Django 2.2.8 on 2020-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200411_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='unique_code',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
