# Generated by Django 2.2.5 on 2019-11-15 21:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
