# Generated by Django 2.2.5 on 2019-11-16 09:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20191115_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
