# Generated by Django 2.2.5 on 2019-11-16 10:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20191116_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
