# Generated by Django 2.2.5 on 2020-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200222_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
