# Generated by Django 2.2.5 on 2020-02-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exams_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField(choices=[(1, 'MCQ(Single option correct)'), (2, 'MCQ(Multiple option correct)'), (3, 'Subjective')], default=1)),
                ('body', models.TextField()),
                ('marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions_in_exam', to='exams.Exams')),
            ],
        ),
    ]
