# Generated by Django 2.2.8 on 2020-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_answer_examsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
