# Generated by Django 2.2.5 on 2020-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_type',
            field=models.CharField(choices=[('1', 'MCQ(Single option correct)'), ('2', 'MCQ(Multiple option correct)'), ('3', 'Subjective')], default=1, max_length=1),
        ),
    ]
