# Generated by Django 2.2.5 on 2020-02-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200229_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q_type',
        ),
    ]
