# Generated by Django 2.2.5 on 2020-02-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_questions_q_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
