# Generated by Django 2.2.5 on 2020-02-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_delete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q_type',
            field=models.CharField(choices=[('1', 'Single_Option_Correct'), ('2', 'Multiple_Option_Correct'), ('3', 'Subjective')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
