# Generated by Django 2.2.5 on 2020-02-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200301_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_type',
            field=models.CharField(choices=[('1', 'MCQ(Single Option Correct)'), ('2', 'MCQ(Multiple Option Correct)'), ('3', 'Subjective')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ans', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Options_for_Questions', to='exams.Questions')),
            ],
        ),
    ]
