# Generated by Django 2.2.8 on 2020-04-11 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200410_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
