# Generated by Django 2.2.8 on 2020-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20200411_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
