# Generated by Django 2.2.5 on 2020-03-10 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20200308_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='Duration',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 7, 14, 25, 770345, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='instructions',
            field=models.TextField(default='jjj'),
            preserve_default=False,
        ),
    ]
