# Generated by Django 2.2.8 on 2020-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20200418_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
