# Generated by Django 2.2.5 on 2020-03-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20200310_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='Duration',
            new_name='duration',
        ),
    ]
