# Generated by Django 2.2.8 on 2020-04-20 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20200419_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, to='exams.Option'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
