# Generated by Django 2.2.5 on 2020-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20200310_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
