# Generated by Django 2.2.5 on 2020-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_questions_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/exams'),
        ),
    ]
