# Generated by Django 2.2.5 on 2020-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_auto_20200319_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/exams/'),
        ),
    ]
