# Generated by Django 2.2.5 on 2020-03-21 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_auto_20200319_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='active_date',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='active_time',
        ),
        migrations.AddField(
            model_name='exams',
            name='active_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
