# Generated by Django 2.2.5 on 2020-03-21 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200321_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='duration',
        ),
        migrations.AddField(
            model_name='exams',
            name='duration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
